services:
  frontend:
    image: frontend-image
    container_name: frontend-container
    build: .
    restart: always
    tty: true
    volumes:
      - ./host-frontend-root/frontend-src-root:/opt/frontend-container-app-root/frontend-src-root
    ports:
      - "5173:5173"  # ポートフォワーディングの設定
    environment:
      - HOST=0.0.0.0  # サーバーのバインドアドレスを設定
