services:
  frontend:
    image: frontend-image
    container_name: frontend-container
    build:
      context: .
      args:
        HOST_SRC_ROOT: ${HOST_SRC_ROOT}
        APP_ROOT: ${APP_ROOT}
    restart: always
    tty: true
    volumes:
      - ${HOST_SRC_ROOT}:${APP_ROOT}
      - exception-volumes:${APP_ROOT}/node_modules
    ports:
      - "5173:5173"  # ポートフォワーディングの設定
    environment:
      - HOST=0.0.0.0  # サーバーのバインドアドレスを設定

volumes:
  exception-volumes:
    name: exception-node_modules